# This is a basic workflow to help you get started with Actions

name: Read RN

# Controls when the action will run. 
on:
  push:
    branches:
      - master
      - release/*
      - ni/test2
    
  workflow_dispatch:
    inputs:
      tags:
        description: 'Build an app with a specific wrapper version'
        required: true
        default: 'Bluedot-React-Native-Plugin release'


jobs:
  read-to-RN:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository to get release notes
        - uses: actions/checkout@master

        - name: Extract files
          uses: a7ul/tar-action@v1.1.0
          id: extract
          with:
            command: x
            cwd: ./
            files: bluedot-react-native-2.1.2.tgz