# This is a basic workflow to help you get started with Actions

name: Read RN

# Controls when the action will run. 
on:
  push:
    branches:
      - master
      - release/*
      - ni/test2
    
  workflow_dispatch:
    inputs:
      tags:
        description: 'Build an app with a specific wrapper version'
        required: true
        default: 'Bluedot-React-Native-Plugin release'
env:
  RN_PATH: "ReleaseNotes.md"

jobs:
  read-to-RN:
     runs-on: ubuntu-latest
     outputs:
      releaseNotes: ${{ steps.read_file.outputs.contents }}
      is_tag_build: ${{ steps.check-tag2.outputs.is_tag_build }}

     steps:
        # check whenever this is a build for tag whenever it's a downstream build or a manual build
        - name: Check 2 Tag
          id: check-tag2
          if: |
           contains(github.ref, '-pre+build.') ||
           contains(github.event.inputs.tag, '-pre+build.')
          run: |
           echo "::set-output name=is_tag_build::true"

        # Checks-out your repository to get release notes
        - name: Checkout code
          uses: actions/checkout@master

        - name: Extract files
          if: ${{ steps.check-tag.outputs.is_tag_build == 'true' }}
          uses: a7ul/tar-action@v1.1.0
          id: extract
          with:
            command: x
            cwd: ./
            files: bluedot-react-native-2.1.2.tgz
      
      
        - name: Set Default ReleaseNotes Path
          id: set-default-path
          run: path = "ReleaseNotes.md"



        - name: Set ReleaseNotes Path
          id: set-path
          if: ${{ steps.check-tag.outputs.is_tag_build == 'true' }}
          run: env.RN_PATH = "./package/ReleaseNotes.md"


        - name: Read RN
          id: read_file
          uses: andstor/file-reader-action@v1
          with:
           path: ${{ env.RN_PATH }}

        - name: File contents
          run: echo "::set-output name=releaseNotes::${{ steps.read_file.outputs.contents }}"
